### ISSUE TITLE
[通用] [站内信] 站内信功能

### ISSUE THREAD

**Issue by AaricChen** [AaricChen/qxcmp-framework#1]

**Comment by cmtt1212** [comment]
系统工具加一个入口，作为发送。 
个人中心加一个入口，作为接受。
 主页加一个消息提醒。

**Comment by cmtt1212** [comment]
所有用户共用一张总表

- id
- user_id
- title
- content
- date
- read

**Comment by cmtt1212** [comment]
做了个大概了。

**Comment by AaricChen** [comment]
Good Job！

回头把代码提了吧   我们在这上面review
